# Generated by Django 2.0.2 on 2018-02-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='html',
        ),
    ]
